package domain;

public enum InformationType {
	DIFFERENCE_OF_DIFFERENCES,
	REVERSED_ENTROPY,
	STATE_PROBABILITY,
	PROBABILITY,
	MUTUAL_INFORMATION,
	ENTROPY_DIFFERENCE_HOPEDFOR,
	ENTROPY,
	ENTROPY_DIFFERENCE,
	ENTROPY_REVERSED
}